<?php

/*
 * This file is part of the Indigo Doctrine Annotation Autoload plugin.
 *
 * (c) Indigo Development Team
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Indigo\Composer\Autoload;

use Composer\Autoload\AutoloadGenerator;

/**
 * @author Márk Sági-Kazár <mark.sagikazar@gmail.com>
 */
class DoctrineAutoloadGenerator extends AutoloadGenerator
{
    /**
     * {@inheritdoc}
     */
    protected function getAutoloadFile($vendorPathToTargetDirCode, $suffix)
    {
        return <<<AUTOLOAD
<?php

// autoload.php @generated by Composer

use Doctrine\Common\Annotations\AnnotationRegistry;

require_once $vendorPathToTargetDirCode . '/autoload_real.php';

\$loader = ComposerAutoloaderInit$suffix::getLoader();

AnnotationRegistry::registerLoader([\$loader, 'loadClass']);

return \$loader;

AUTOLOAD;
    }
}
